### PR TITLE
[ADD] Custom module for OCA Instance

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Add new module to analyze github activities.

Thanks for your review.

CC : @pedrobaeza, @bjoliveau, @jgrandguillaume, @gurneyalex, @bguillot, @StefanRijnhart

**Comment by gurneyalex** [comment]
@legalsylvain please resubmit on https://github.com/OCA/interface-github

**Comment by pedrobaeza** [comment]
We can close this one in favor of https://github.com/OCA/interface-github/pull/1

**Comment by legalsylvain** [comment]
No. this PR contains custom module.

**Comment by pedrobaeza** [comment]
OK, sorry.

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
