### PR TITLE
[ADD] 'website_oca_psc_team' module to display PSC teams in website.

### PR DESCRIPTION
**Pull request by st-aprajapati**

### CODE REVIEW

**Comment by elicoidal** [comment]
Functional tests:
* demo data repository_1 key is duplicated
* When creating project there is a warning "Number of characters must be less then or equal to 75. " but we do not know which field is wrong (short description).
* PSC Category description should be html
* IMO we should have for the category a short description (<200 char for example) as current one might be too long (see screenshot). Long description could be displayed with a "more" button or second option, only display first 200 char of description and display the rest with `more`

image

* It is not possible to click on the representative / member and access their profile.
* When clicking on the repo link the content should be open in another tab
* Nice to have: a photo for the PSC Category

@st-aprajapati @sbidoul

**Review by jgrandguillaume — COMMENTED** [review]
Hi,

Thanks for the work. Functional test went well on my side. I like the look and feel.

Two same remark than Eric:

- It is not possible to click on the representative / member and access their profile.
- When clicking on the repo link the content should be open in another tab

A part of this, :+1: 

Joël

**Comment by st-aprajapati** [comment]
@elicoidal Thanks for the review. I will update the changes suggested by you. I want confirm few points:

- PSC Category description:
          1) HTML field -  I don’t mind to declare it as html. As of now, We have applied font style in description field as per current OCA website style. If we change it to html field, then user will have to take care about styling. 
          2) Display ‘more’ if description exceeds more than 200 chars - @sbidoul Can you please put your thoughts? 

- Link on representative/member and photo for the PSC Category: Representative and members are res.users entity in project. And we have to link it as partner entity in frontend (i.e. /partners). I am assuming that, we have to display representative/members **if they are website published.**

- Photo for the PSC Category - @sbidoul can you please put your thoughts?

**Comment by st-aprajapati** [comment]
> Hi,
> 
> Thanks for the work. Functional test went well on my side. I like the look and feel.
> 
> Two same remark than Eric:
> 
> * It is not possible to click on the representative / member and access their profile.
> * When clicking on the repo link the content should be open in another tab
> 
> A part of this, 
> 
> Joël

Thanks for the review and suggestions.

**Comment by sbidoul** [comment]
Thanks for this work. Looks very good overall. The code is clean, with tests and even a tour :) Great job.

Regarding category description, I personally don't think we'll ever have very long descriptions for PSC categories. So keeping them as text is fine with me. An icon is not mandatory for PSC categories either IMO, that could even create confusion with PSC icons.

A link to the partner profile seems important though.

Can you also foresee a default icon for PSC? we may not have all icons when we launch initially.

I'm merging this, so you can do another PR with the last details.

**Comment by sbidoul** [comment]
So, a few requests for a new PR, after deploying on https://odoo-community.org:

- what do you suggest to position the menu where we want (in case we don't want it as a top level menu)

image

- shorten repo name (no need to have https://github.com displayed), so it does not wrap.

image

**Comment by st-aprajapati** [comment]
Thanks for your review and comments @sbidoul
 
Regarding,
- Default icon for PSC - We have already displayed OCA icon If image is not uploaded in project. Please let me know if you want to change it. I am not sure why it was not displaying a few hours ago in live site. But now, it is displaying. (https://odoo-community.org/psc-teams)
- Position of the ‘PSC Teams’ menu: IMO, You should configure the parent menu as ‘Resources’ instead of ‘Top Menu’ and remove the existing ‘Project Steering Committees’ menu from the backend settings.
- I will create a PR with following modifications:
     - Link to representative/members
     - Shorten repo name (e.g. OCA/account-analytic)
     - Few changes suggested by elicoidal 
             - Remove ‘repository_1’ key which is duplicated from demo data.
             - Update warning message for short description.
             - Repo link should be opened in new tab.

**Comment by OSevangelist** [comment]
Dear all i had a look at the functionality which overall looks fine to me. What i mis though is an way to "search" for a specific PSC / Repo (for instance as a search field atop of the page)

PSC Teams | Website localhost - Mozilla Firefox_623

**Pull request merged**
